<div class="row">
	<?php self::renderView('alerts/_errors'); ?>
	<?php self::renderView('alerts/_success'); ?>
</div>

<div class="row">
  <div class="col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">
    <div class="thumbnail">
      <img src="/assets/img/orion_banner.jpg" alt="...">
      <div class="caption text-center">
        <h3><em>Orion Framework</em></h3>
        <h5>¡Welcome!</h5>
      </div>
    </div>
  </div>
</div>
