<div class="container">
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><b><?php echo $this->getPageTitle() ?></b></h1>
                </div>
                 <div class="panel-body">
                     <div class="clearfix"></div>
                    <?php self::renderView('alerts/_errors'); ?>

                    <form action="/user/store" method="post" accept-charset="utf-8">

                        <div class="form-group <?php echo ($this->errors['name']) ? 'has-error' : '' ?>">
                            <label for="title" class="control-label">Name</label>
                            <input type="text" name="name" class="form-control" value="<?php echo (isset($this->inputs['name'])) ? $this->inputs['name'] : '' ?>">
                            
                            <?php if($this->errors['name']): ?>
                                <span class="help-block"><?php echo $this->errors['name'] ?></span>
                            <?php endif; ?>

                        </div>

                        <div class="form-group <?php echo ($this->errors['email']) ? 'has-error' : '' ?>">
                            <label for="title" class="control-label">Email</label>
                            <input type="text" name="email" class="form-control" value="<?php echo (isset($this->inputs['email'])) ? $this->inputs['email'] : '' ?>">
                            
                            <?php if($this->errors['email']): ?>
                                <span class="help-block"><?php echo $this->errors['email'] ?></span>
                            <?php endif; ?>

                        </div>

                        <div class="form-group <?php echo ($this->errors['password']) ? 'has-error' : '' ?>">
                            <label for="title" class="control-label">Password</label>
                            <input type="password" name="password" class="form-control" value="<?php echo (isset($this->inputs['password'])) ? $this->inputs['password'] : '' ?>">
                            
                            <?php if($this->errors['password']): ?>
                                <span class="help-block"><?php echo $this->errors['password'] ?></span>
                            <?php endif; ?>

                        </div>

                        <div>
                            <a href="/posts" class="btn btn-default"><i class="glyphicon glyphicon-arrow-left" aria-hidden="true"></i> Cancel</a>
                            <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save" aria-hidden="true"></i> Save</button>
                        </div>

                    </form>

                 </div>
            </div>
           
            
        </div>
    </div>
</div>