<div class="container">
    <div class="row">
        <h1 class="h1 col-xs-12"><?php echo $this->getPageTitle() ?></h1>

        <div class="clearfix"></div>
        <?php self::renderView('alerts/_errors'); ?>

        <form action="/post/store" method="post" accept-charset="utf-8">
            <div class="col-sm-10">
            	<div class="form-group">
                    <label for="title" class="control-label">Title</label>
                    <input type="text" name="title" class="form-control" value="">
                </div>

                <div class="form-group">
                    <label for="title" class="control-label">Content</label>
                    <textarea name="content" class="form-control" rows="15"></textarea>
                </div>

                <div class="col-xs-12">
                    <a href="/posts" class="btn btn-default">Cancel</a>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group <?php echo ($this->errors['category_id']) ? 'has-error' : '' ?>">
                    <label for="title" class="control-label">Categories</label>
                    <?php foreach ($this->view->categories as $cat) : ?>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="category_id[]"
                                value="<?php echo $cat->id ?>"> <?php echo $cat->name ?>
                            </label>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

        </form>
    </div>
</div>