<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/favicon.png" type="image/x-icon">
    <title><?php echo self::getPageTitle('-'); ?> Orion Micro Framework</title>
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>

  	<?php require_once __DIR__ . "/menu.phtml" ?>
    <?php self::content(); ?>

    <!-- jQuery-->
    <script src="/assets/js/jquery-3.3.1.min.js"></script>
    <!-- bootstrap js -->
    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>